TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.CIVI = {}

TUNING.CIVI_HUNGER = 175
TUNING.CIVI_SANITY = 175
TUNING.CIVI_HEALTH = 175

TUNING.WEAPONPLAN = GetModConfigData("WEAPONPLAN")
TUNING.GEARPLAN = GetModConfigData("GEARPLAN")
