local _G = GLOBAL

_G.STRINGS.NAMES.CIVI = "Civi"

-- starting info --
_G.STRINGS.CHARACTER_SURVIVABILITY.civi = _G.STRINGS.CHARACTER_SURVIVABILITY.wilson
_G.TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.CIVI={}

_G.TUNING.CIVI_HUNGER = 175
_G.TUNING.CIVI_SANITY = 175
_G.TUNING.CIVI_HEALTH = 175